version: "3.4"

services:
  todo-app:
    container_name: todo-app
    build: .
    volumes:
      - .env.docker:/app/.env
      - .:/usr/src/app
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb://user:pass@todo-mongo:27017/cluster0?retryWrites=false
      - JWT_SECRET=secret
      - NODE_ENV=development
    depends_on:
      - todo-mongo

  todo-mongo:
    image: mongo:latest
    container_name: todo-mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - "./mongo-entrypoint/entrypoint.js:/docker-entrypoint-initdb.d/entrypoint.js:ro"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  todo-mongo-express:
    image: mongo-express
    container_name: todo-mongo-express
    restart: always
    ports:
      - 8081:8081
    volumes:
      - .:/usr/src/app/backend
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@todo-mongo:27017/
    depends_on:
      - todo-mongo

volumes:
  data:
