version: "3.4"

services:
  todo-app:
    container_name: todo-app
    build: .
    volumes:
      - .env.docker:/app/.env
      - .:/usr/src/app
    ports:
      - 5555:5000
    depends_on:
      - todo-mongodb

  todo-mongodb:
    image: mongo:latest
    container_name: todo-mongodb
    ports:
      - "27018:27017"
    volumes:
      - data:/data/db

  todo-mongo-express:
    image: mongo-express
    container_name: todo-mongo-express
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/app/backend
    environment:
      - ME_CONFIG_MONGODB_SERVER=todo-mongodb
    depends_on:
      - todo-mongodb

volumes:
  data:
